[package]
name = "sniff"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
crossterm = "0.28.1"

[[bin]]
name = "sniff"
src = "src/main.rs"

[lib]
name = "toolkit"
path = "src/lib.rs"

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
